### ISSUE TITLE
Remove compute_node_connectivity.yaml

### ISSUE THREAD

**Issue by ukalifon** [rthallisey/clapper#95]
The validator calls "ip r" and parses for default routes. If you have multiple nics it fails because it tries to ping many IPs on the same command line.

This validator should be removed as the test is implemented in the Tripleo Heat Templates anyways.

**Comment by tomassedovic** [comment]
Thank! We have removed the validation from the `ansible1.9` branch:

https://github.com/rthallisey/clapper/pull/94

If you do a git pull, it should be gone.
